# Site settings
author: Heeraj D Ramsanai
title: My Software Engineering Journey
header-img: img/home-bg.png
email: ramsanai_heeraj@live.com
copyright_name: Heeraj D Ramsanai
description: > # this means to ignore newlines until "baseurl:"
  My Journey as a beginner seeking a software engineer career
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Heerajr

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
